# -*- coding: utf-8 -*-
"""pregunta 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CMXxPfw9P00Res6b-VeWWYRnb4rmTgjN

**PREGUNTA 1**

INTEGRANTES:
- Gutierrez Gutierrez Danahe Arleni
- Figueroa Gonzalez Giner Bush
- Otazú Quispe Diego Armando

Intercambiar los valores de 2 variables
"""

# Para solicitar que ingrese los valores de A y B
A = input("Ingrese el valor de A: ")
B = input("Ingrese el valor de B: ")

# Mostrar los datos de entrada de A y B
print("Datos de entrada:")
print("A =", A)
print("B =", B)

# Intercambiar los valores de A y B
A, B = B, A

# Mostrar los datos de salida
print("\nDatos de salida:")
print("A =", A)
print("B =", B)

