# -*- coding: utf-8 -*-
"""Pregunta 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mNnMFdt3JGTu3j2Kx4Eh69wpHC4zkH5E

**PREGUNTA 2**

INTEGRANTES:
- Gutierrez Gutierrez Danahe Arleni
- Figueroa Gonzalez Giner Bush
- Otazú Quispe Diego Armando

Dado n, hallar la suma de los n primeros números naturales
"""

n = int(input("n: "))
suma = 0

for i in range(1, n + 1):
    suma += i

print(f"Sumatoria: {suma}")